CREATE TABLE subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(500),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT,
    stem TEXT NOT NULL,
    answer TEXT,
    knowledge_points VARCHAR(1000),
    difficulty VARCHAR(40),
    layout_json TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE subject_materials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    file_name VARCHAR(255),
    material_type VARCHAR(40),
    ingest_status VARCHAR(40),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE grading_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    file_name VARCHAR(255),
    total_score NUMERIC(8,2),
    result_json TEXT,
    teacher_edited_json TEXT,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE student_exam_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    exam_name VARCHAR(160),
    class_name VARCHAR(120),
    grade_name VARCHAR(120),
    student_no VARCHAR(80),
    student_name VARCHAR(120),
    total_score NUMERIC(8,2)
);

CREATE TABLE student_question_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_exam_score_id BIGINT NOT NULL,
    question_no VARCHAR(40),
    score NUMERIC(8,2),
    knowledge_point VARCHAR(255)
);

CREATE TABLE learning_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    scope_type VARCHAR(40),
    scope_name VARCHAR(120),
    report_text TEXT,
    created_at TIMESTAMP NOT NULL
);

